name = "Don't Dye Together"
author = "P1x3l101"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "09615a7dfe4950b82fb12c781efce7807b7bdf29739707ef419ec3b7f8e12935"

[versions]
forge = "47.4.0"
lwjgl3 = "3.3.1"
minecraft = "1.20.1"
unsup = "1.1.3"
